In [18]:
#Create a 2D array using random array with 3 row 5 columns.
import numpy as np
array = np.random.randint(10,size=(3,5))
print(array)

[[8 7 2 5 9]
 [0 1 0 0 8]
 [8 8 0 1 0]]


In [12]:
#Create a variable which will give you random value from a set of [3, 5, 6,7 ].
import numpy as np
x = [3,5,6,7]
y = np.random.choice(x)
print(y)

6


In [14]:
#Create a multidimensional array first and then convert it to 1D array.
import numpy as np
A = np.array([[1,2,34],[23,45,67],[42,45,67]])
B = A.flatten()
print(B)

[ 1  2 34 23 45 67 42 45 67]


In [16]:
#Create a 3D array with 4 arrays, 3 rows, 4 columns.
import numpy as np
C = np.array([[[12,23,45,32],[22,34,54,34],[32,45,67,43]],
             [[23,43,45,65],[23,45,67,89],[43,56,78,90]],
             [[32,34,56,78],[12,34,56,78],[98,76,54,32]],
             [[34,56,76,87],[34,54,67,89],[43,56,98,89]]])
print(C)

[[[12 23 45 32]
  [22 34 54 34]
  [32 45 67 43]]

 [[23 43 45 65]
  [23 45 67 89]
  [43 56 78 90]]

 [[32 34 56 78]
  [12 34 56 78]
  [98 76 54 32]]

 [[34 56 76 87]
  [34 54 67 89]
  [43 56 98 89]]]


In [29]:
#Write a code to find out mean, median and mode for array in NumPy.
import numpy as np
import statistics as sd
print("mean =",np.mean(B))
print("median = ",np.median(B))
print("mode =",sd.mode(B))

mean = 36.22222222222222
median =  42.0
mode = 45


In [31]:
#Write a code to create a variable in NumPy to get values between 0 to 100.
import numpy as np
E = np.arange(0,100)
print(E)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [32]:
#Arr_ = numpy.array([[1,2,3,4,5],[6,7,8,9,10]]. From the 2 nd row slice elements from 1 to 4.
import numpy as np
Arr_ = np.array([[1,2,3,4,5],[6,7,8,9,10]])
se = Arr_[1,1:5]
print(se)


[ 7  8  9 10]


In [34]:
#Arr_ = numpy.array([[1,2,3,4,5],[6,7,8,9,10]]. From the 1st row slice elements from 1,3,5.
import numpy as np
Arr_ = np.array([[1,2,3,4,5],[6,7,8,9,10]])
sp = Arr_[0,[1,3,4]]
print(sp)


[2 4 5]


In [38]:
#Write a code to create a variable in NumPy to get 5 random values between 0 to 100.
import numpy as np
G = np.random.randint(0,100,size=5)
print(G)

[11 76 58 84  8]


In [43]:
'''Arr = numpy.array([1,2,3,4,5,6,10])
Arr1 = numpy.array([13,14,12,16,17,18,9,10])
Write a code to find the max value and min value.'''
import numpy as np
Arr = np.array([1,2,3,4,5,6,10])
Arr1 = np.array([13,14,12,16,17,18,9,10])
print("Arrmax =",max(Arr),"Arrmin =",min(Arr))
print("Arr1max =",max(Arr1),"Arr1min =",min(Arr1))

Arrmax = 10 Arrmin = 1
Arr1max = 18 Arr1min = 9
